### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mageru** [sergeymakinen/vscode-github-theme#1]
Getting "Couldn't find a compatible version of GitHub 3 with this version of Code."

Running x64 on Windows 10.

**Comment by mageru** [comment]
![image](https://user-images.githubusercontent.com/290324/30468203-e28938da-99b7-11e7-9201-a6be23d80663.png)

**Comment by sergeymakinen** [comment]
Which VS Code's version do you use? At this moment, this theme is targeted for 1.16. I have not tested it on earlier versions but I will.

**Comment by sergeymakinen** [comment]
It should be fine since https://github.com/sergeymakinen/vscode-github-theme/commit/de902b8c67bdd981b5d40bb1362a068b9a70ed2b.
